require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 3.0
  NewCops: enable
Layout/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 30
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "[]"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/**/*'
