version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    volumes:
      - .:/var/www/app
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
  mail:
    image: yappabe/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  postgres_data:
