default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database
development:
  <<: *default
  database: pikabu_development
test:
  <<: *default
  database: pikabu_test
production:
  <<: *default
  database: pikabu_production
  username: pikabu
  password: <%= ENV['PIKABU_DATABASE_PASSWORD'] %>
